# -*- coding: utf-8 -*-
"""TRANSCRIPTOR WHISPER PARLA IA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vc31q7XgjeJGU-IjXWSVaQiWz3l9xkO3

## WHISPER IA PARA TRANSCRIPCIÓN

<img src="https://i.ytimg.com/vi/BQErsh_Iff8/maxresdefault.jpg" width="400" height="200">

> Con esta herramienta podrán hacer las transcripciones, los formatos aceptables son: MP3, MP4 y el más recomendable en caso de que tengan problemas con los dos anteriores sería el formato WAV.


> Cabe destacar que toma su tiempo para realizar la transcripción.



> Para ejecutar cada uno de lo pasos, darle únicamente clik en el ícono de play ▶ y esperar que finalice el proceso.



> Seguir cada uno de los pasos a continuación:
"""

#@title 1-💽 Ejecutar esta opción para intalar la librería.
!pip install git+https://github.com/openai/whisper.git -q && pip install jiwer -q && pip install pydub -q && echo "Los paquetes whisper, jiwer y pydub se han instalado correctamente."

#@title 2-💽 Ejecutar esta opción para iniciar el entorno 
!pip install whisper -q && echo "El paquete whisper se ha instalado correctamente." || echo "Se ha producido un error durante la instalación."

#@title 3-🎙️ **Transcribe ** [Elige el Audio de la Reunión]
import whisper
import datetime
from google.colab import files
from pydub import AudioSegment

# Crea el cuadro de diálogo de selección de archivos
uploaded = files.upload()

# Obtiene la ruta del archivo cargado
audio_file_path = list(uploaded.keys())[0]

# Convierte el archivo de audio a formato WAV
audio_file = AudioSegment.from_file(audio_file_path)
audio_file_path_wav = audio_file_path.split(".")[0] + ".wav"
audio_file.export(audio_file_path_wav, format="wav")

# Transcribe el audio usando el modelo Whisper
model = whisper.load_model("medium")
result = model.transcribe(audio_file_path_wav)

#@title 4-📘 Texto Plano y Texto por Minutos de la Transcripción

# Guarda el resultado de la transcripción en un archivo de texto plano
with open("resultado_transcripcion.txt", "w") as archivo_plano:
    archivo_plano.write(result["text"])
    print("El resultado de la transcripción se ha guardado en el archivo 'resultado_transcripcion.txt'")

# Divide el texto por minuto y lo guarda en un archivo
with open("resultado_transcripcion_por_minuto.txt", "w") as archivo_minuto:
    text = result["text"]
    duration = audio_file.duration_seconds
    for i in range(int(duration//60)+1):
        start_time = datetime.timedelta(minutes=i)
        end_time = datetime.timedelta(minutes=i+1)
        start_index = int(start_time.total_seconds()*len(text)/duration)
        end_index = int(end_time.total_seconds()*len(text)/duration)
        archivo_minuto.write(f"Minuto {i+1} ({start_time} - {end_time}): {text[start_index:end_index]}\n")
    print("El resultado de la transcripción por minuto se ha guardado en el archivo 'resultado_transcripcion_por_minuto.txt'")